### ISSUE TITLE
Add unzip function (feature request)

### ISSUE THREAD

**Issue by martin-rueegg** [troydm/central#3]
It would be fantastic to be able do unzip downloaded files.

It could be done using the [rubyzip](https://github.com/rubyzip/rubyzip) module (`gem install rubyzip`) and the following code:

```
require 'zip'

def extract_zip(file, destination)
  FileUtils.mkdir_p(destination)

  Zip::File.open(file) do |zip_file|
    zip_file.each do |f|
      fpath = File.join(destination, f.name)
      FileUtils.mkdir_p(File.dirname(fpath))
      zip_file.extract(f, fpath) unless File.exist?(fpath)
    end
  end
end
```

Then a file could be unzipped like this:
`extract_zip('file.zip', 'tmp')`

Source: https://stackoverflow.com/a/60268551

Would it be possible to add `rubyzip` as a dependency and add the above function?

**Comment by troydm** [comment]
use latest v0.3.3 central extract command that uses unzip tool which works a lot faster
